version: '3'

services:
  php:
    build: ./.docker/php-fpm
    volumes:
    - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    depends_on:
    - mysql

  web:
    image: nginx:latest
    ports:
    - "8888:80"
    volumes:
    - ./ineat:/var/www/ineat
    - ./nginx/ineat.conf:/etc/nginx/default.conf
    depends_on:
    - php

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3333:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf4_phpmyadmin
    ports:
    - 8080:80
    links:
    - mysql
